# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editor.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tadWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tadWidget.setGeometry(QtCore.QRect(0, 0, 1280, 660))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(10)
        self.tadWidget.setFont(font)
        self.tadWidget.setObjectName("tadWidget")
        self.tabEdit = QtWidgets.QWidget()
        self.tabEdit.setObjectName("tabEdit")
        self.label = QtWidgets.QLabel(self.tabEdit)
        self.label.setGeometry(QtCore.QRect(30, 50, 540, 360))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../util/insert.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.stackedWidget = QtWidgets.QStackedWidget(self.tabEdit)
        self.stackedWidget.setGeometry(QtCore.QRect(720, 180, 301, 401))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.gaussianBlur = QtWidgets.QWidget()
        self.gaussianBlur.setObjectName("gaussianBlur")
        self.dial = QtWidgets.QDial(self.gaussianBlur)
        self.dial.setGeometry(QtCore.QRect(110, 80, 81, 101))
        self.dial.setObjectName("dial")
        self.pushButton = QtWidgets.QPushButton(self.gaussianBlur)
        self.pushButton.setGeometry(QtCore.QRect(110, 330, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.gaussianBlur)
        self.label_2.setGeometry(QtCore.QRect(120, 200, 55, 16))
        self.label_2.setAutoFillBackground(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.gaussianBlur)
        self.label_3.setGeometry(QtCore.QRect(110, 50, 101, 31))
        self.label_3.setObjectName("label_3")
        self.stackedWidget.addWidget(self.gaussianBlur)
        self.sobelEdge = QtWidgets.QWidget()
        self.sobelEdge.setObjectName("sobelEdge")
        self.checkBox = QtWidgets.QCheckBox(self.sobelEdge)
        self.checkBox.setGeometry(QtCore.QRect(110, 220, 121, 20))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.sobelEdge)
        self.checkBox_2.setGeometry(QtCore.QRect(110, 250, 111, 20))
        self.checkBox_2.setObjectName("checkBox_2")
        self.label_4 = QtWidgets.QLabel(self.sobelEdge)
        self.label_4.setGeometry(QtCore.QRect(90, 40, 131, 21))
        self.label_4.setObjectName("label_4")
        self.horizontalSlider = QtWidgets.QSlider(self.sobelEdge)
        self.horizontalSlider.setGeometry(QtCore.QRect(80, 100, 160, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_5 = QtWidgets.QLabel(self.sobelEdge)
        self.label_5.setGeometry(QtCore.QRect(130, 130, 55, 16))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.pushButton_2 = QtWidgets.QPushButton(self.sobelEdge)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 330, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.stackedWidget.addWidget(self.sobelEdge)
        self.cannyEdge = QtWidgets.QWidget()
        self.cannyEdge.setObjectName("cannyEdge")
        self.stackedWidget.addWidget(self.cannyEdge)
        self.average = QtWidgets.QWidget()
        self.average.setObjectName("average")
        self.label_6 = QtWidgets.QLabel(self.average)
        self.label_6.setGeometry(QtCore.QRect(100, 60, 131, 21))
        self.label_6.setObjectName("label_6")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.average)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(80, 120, 160, 22))
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.label_7 = QtWidgets.QLabel(self.average)
        self.label_7.setGeometry(QtCore.QRect(130, 160, 55, 16))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.pushButton_3 = QtWidgets.QPushButton(self.average)
        self.pushButton_3.setGeometry(QtCore.QRect(110, 250, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.stackedWidget.addWidget(self.average)
        self.sharpen = QtWidgets.QWidget()
        self.sharpen.setObjectName("sharpen")
        self.stackedWidget.addWidget(self.sharpen)
        self.comboBox = QtWidgets.QComboBox(self.tabEdit)
        self.comboBox.setGeometry(QtCore.QRect(820, 120, 121, 41))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.tadWidget.addTab(self.tabEdit, "")
        self.tabRegister = QtWidgets.QWidget()
        self.tabRegister.setObjectName("tabRegister")
        self.label_8 = QtWidgets.QLabel(self.tabRegister)
        self.label_8.setGeometry(QtCore.QRect(670, 40, 540, 360))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("../util/Toussaint 2 Noon.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tabRegister)
        self.label_9.setGeometry(QtCore.QRect(60, 40, 540, 360))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("../util/Toussaint 1 Morning.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.tadWidget.addTab(self.tabRegister, "")
        self.tabSegment = QtWidgets.QWidget()
        self.tabSegment.setObjectName("tabSegment")
        self.tadWidget.addTab(self.tabSegment, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuRegister = QtWidgets.QMenu(self.menubar)
        self.menuRegister.setObjectName("menuRegister")
        self.menuSegment = QtWidgets.QMenu(self.menubar)
        self.menuSegment.setObjectName("menuSegment")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionFilter = QtWidgets.QAction(MainWindow)
        self.actionFilter.setObjectName("actionFilter")
        self.actionResize = QtWidgets.QAction(MainWindow)
        self.actionResize.setObjectName("actionResize")
        self.actionCrop = QtWidgets.QAction(MainWindow)
        self.actionCrop.setObjectName("actionCrop")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionSave)
        self.menuEdit.addAction(self.actionFilter)
        self.menuEdit.addAction(self.actionResize)
        self.menuEdit.addAction(self.actionCrop)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuRegister.menuAction())
        self.menubar.addAction(self.menuSegment.menuAction())

        self.retranslateUi(MainWindow)
        self.tadWidget.setCurrentIndex(1)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Apply"))
        self.label_2.setText(_translate("MainWindow", "0.4"))
        self.label_3.setText(_translate("MainWindow", "Choose Sigma"))
        self.checkBox.setText(_translate("MainWindow", "Edges along X"))
        self.checkBox_2.setText(_translate("MainWindow", "Edges along Y"))
        self.label_4.setText(_translate("MainWindow", "Select Kernel Size"))
        self.label_5.setText(_translate("MainWindow", "5"))
        self.pushButton_2.setText(_translate("MainWindow", "Apply"))
        self.label_6.setText(_translate("MainWindow", "Select Kernel Size"))
        self.label_7.setText(_translate("MainWindow", "5"))
        self.pushButton_3.setText(_translate("MainWindow", "Apply"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Gaussian Blur"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Sobel Edge"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Canny Edge"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Average"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Sharpen"))
        self.tadWidget.setTabText(self.tadWidget.indexOf(self.tabEdit), _translate("MainWindow", "Edit"))
        self.tadWidget.setTabText(self.tadWidget.indexOf(self.tabRegister), _translate("MainWindow", "Register"))
        self.tadWidget.setTabText(self.tadWidget.indexOf(self.tabSegment), _translate("MainWindow", "Segment"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuRegister.setTitle(_translate("MainWindow", "Register"))
        self.menuSegment.setTitle(_translate("MainWindow", "Segment"))
        self.actionNew.setText(_translate("MainWindow", "New "))
        self.actionNew.setStatusTip(_translate("MainWindow", "Open new image for editing"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setStatusTip(_translate("MainWindow", "Save Image"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionFilter.setText(_translate("MainWindow", "Filter"))
        self.actionResize.setText(_translate("MainWindow", "Resize "))
        self.actionCrop.setText(_translate("MainWindow", "Crop"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
